# Eurytemora Herdmani Size Morph Project Lab Notebook

## 2025-03-11

Went over gitflow steps:\
1) Start session by opening the R proj file\
2) Go to panel and select Pull icon

3\) Make changes\
4) Hit Commit button, select file you want to stage, write commit message, hit the commit button, hit the push button

5\) Repeat as needed\
6) Final Pull\
7) Final Push

Sample: ARM V2 2024-8-19

protocol was followed, two pipettes were used from the sample, 10 copepods were gathered and imaged.

## 2025-03-13

Sample: ARM V2 2024-8-19

Protocol was followed, 10 copepods were gathered and imaged. The scale bar had to be done two times. Size measurements were started today.

To do: finish size measurements for the samples taken

## 2025-03-18

Sample: ARM V2 2024-8-9

Protocol was followed with 10 copepod samples. They were imaged and measured and exploratory analysis was started

To do= make plot look nice, fill and color, pull pictures for small individuals and double check , make plan on where analysis is gonna go, write up brief sentence (couple sentences) about figure

## 2025-03-25

Sample: GMS V2 2024-8-19

Protocol was followed for 30 samples with 10, 9, and 11 on each well plate

## 2025-03-27

Sample: EBM S1 2024-8-19

This sample has very low abundances of Eurytemora, 1st individual dried up so measurement may look weird

Copepod 1 was unable to get imaged due to flattening and inability to turn on its side

individuals 1,2,3, are Herdmani,

Individuals 4, 5, 6, 7, 8, 9 are Americana

## 2025-04-01

Sample: PIM V2 2024-8-19

15 individuals were taken from this site and they were imaged.

## 2025-04-03

Sample: ARM S1 2024-8-19

30 individuals were taken from this site and they were imaged.

## 2025-04-08

Sample: GMS O3 2024-8-19

30 individuals were taken from this site and imaged

## 2025-04-10

Sample: EBM V2 2024-8-19

30 individuals were sampled

## 2025-04-11

Sample: EBM O3 2024-8-19

30 individuals were sampled and imaged

## 2025-04-15

Sample: GMS S1 2024-8-19

7 individuals were sampled and imaged

## 2025-04-17

Sample: ARM O3 2024-8-19

30 individuals were sampled and imaged.

## 2025-04-18

Sample: PIM O3 2024-8-19

30 individuals were sampled and imaged.
